language: Java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_deploy:
- ./gradlew releaseZip
deploy:
  provider: releases
  api_key:
    secure: "e8b086d1-b5ca-4504-8baf-7f55a085b37d"
  file_glob: true
  file: "./build/libs/JAlgoArena-API-*.zip"
  skip_cleanup: true
  on:
    repo: kostekman/JAlgoArena-API
    tags: true
